KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/KKday.Web.OCBT.csproj
KKday.Web.OCBT/Models/Model/DataModel/ComboSupplierModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs

KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/KKday.Web.OCBT.csproj
KKday.Web.OCBT/Models/Model/DataModel/ComboSupplierModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs

[OCBT]Update ResponseJson with java

---

KKday.Web.OCBT/KKday.Web.OCBT.csproj
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Model/Product/QueryWMSProductModel.cs
KKday.Web.OCBT/Models/Model/Product/WMSProductModel.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs

KKday.Web.OCBT/KKday.Web.OCBT.csproj
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Model/Product/QueryWMSProductModel.cs
KKday.Web.OCBT/Models/Model/Product/WMSProductModel.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs

[OCBT]update CallBackJava method  @youngchen123

---

KKday.Web.OCBT/AppCode/CommonTool.cs
KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/CartBooking/CartBookingRsModel.cs
KKday.Web.OCBT/Models/Model/CartBooking/ConfirmBookingValidModel.cs
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Models/Model/DataModel/receiveListModel.cs
KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/WMSQueryOrderModel.cs
KKday.Web.OCBT/Models/Model/Product/ComboInfoModel.cs
KKday.Web.OCBT/Models/Model/Product/QueryWMSProductModel.cs
KKday.Web.OCBT/Models/Model/Product/WMSProductModel.cs
KKday.Web.OCBT/Models/Model/Product/WMSProductModuleModel.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs

KKday.Web.OCBT/AppCode/CommonTool.cs
KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/CartBooking/CartBookingRsModel.cs
KKday.Web.OCBT/Models/Model/CartBooking/ConfirmBookingValidModel.cs
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Models/Model/DataModel/receiveListModel.cs
KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/WMSQueryOrderModel.cs
KKday.Web.OCBT/Models/Model/Product/ComboInfoModel.cs
KKday.Web.OCBT/Models/Model/Product/QueryWMSProductModel.cs
KKday.Web.OCBT/Models/Model/Product/WMSProductModel.cs …

[OCBT]Update BookingFLow

---

KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/Models/Model/DataModel/RequestJavaModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Service/VoucherBackgroundService.cs

KKday.Web.OCBT/Controllers/V1/ComboBookingController.cs
KKday.Web.OCBT/Models/Model/DataModel/RequestJavaModel.cs
KKday.Web.OCBT/Models/Model/DataModel/ResponseJavaModel.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Service/VoucherBackgroundService.cs

[OCBT]Update RequestJavaModel

---

KKday.Web.OCBT/Service/OrderBackgroundService.cs

KKday.Web.OCBT/Service/OrderBackgroundService.cs

[OCBT]Add Switch in orderbackground

---

KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/DataModel/BookingRequestModel.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs

[OCBT]Bug Fixed: Create Order Error

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Bug Fixed:mapping skus error

---

KKday.Web.OCBT/Models/Model/Product/ComboInfoModel.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Models/Model/Product/ComboInfoModel.cs

[OCBT]Update Voucher, bookingModel and comboModel

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Update Create_User insert BOOKING_DTL

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Update Monitor_start_datetime

---

KKday.Web.OCBT/Models/Model/DataModel/BookingDtlModel.cs
KKday.Web.OCBT/Models/Repository/OrderRepository.cs
KKday.Web.OCBT/Service/VoucherBackgroundService.cs

1. DTL.DataModel:voucher_file_info=>List<string>
2. Slack通知
3. 每筆Q為一個Task
4. 尚未callback母單才取出
5. 檢查子單數量(Total = Process + VoucherOK)

Update Voucher BackgroundService

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

Bug Fixed:Update JAVA url

---

KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Models/Repository/BookingRepository.cs

[OCBT]Bug Fixed:Update Combo Repository getComboProd

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Update Nullable with callbackJava

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Bug Fixed:orderMapping Error

---

KKday.Web.OCBT/Models/Repository/BatchJobRepository.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Models/Repository/OrderRepository.cs

KKday.Web.OCBT/Models/Repository/BatchJobRepository.cs
KKday.Web.OCBT/Models/Repository/BookingRepository.cs
KKday.Web.OCBT/Models/Repository/OrderRepository.cs

[OCBT]update b2dUserOid and OcbtUserOid

---

KKday.Web.OCBT/Models/Model/Order/WMSQueryOrderModel.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Models/Model/Order/WMSQueryOrderModel.cs

[OCBT]Bug Fixed:channelOid is null exception

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Update GL error

---

KKday.Web.OCBT/Controllers/V1/BatchJobController.cs
KKday.Web.OCBT/Models/Model/DataModel/CurrencyModel.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Controllers/V1/BatchJobController.cs
KKday.Web.OCBT/Models/Model/DataModel/CurrencyModel.cs

[OCBT]Bug Fixed:Update Combo Producte

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs

[OCBT]Bug Fixed: Add request_uuid with queue

---

KKday.Web.OCBT/Models/Repository/ComboRepository.cs
KKday.Web.OCBT/Service/OrderBackgroundService.cs
KKday.Web.OCBT/Service/VoucherBackgroundService.cs

KKday.Web.OCBT/Service/OrderBackgroundService.cs
KKday.Web.OCBT/Service/VoucherBackgroundService.cs

[OCBT]Bug Fixed:MstOrder is openDate Order and Update Timer With 10 sec

---

KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/OmdlConverter.cs
KKday.Web.OCBT/Models/Repository/ComboRepository.cs

KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/OmdlConverter.cs

[OCBT]Bug Fixed:ConverterOmdl and Booking Fail Error

---

KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/OmdlConverter.cs

KKday.Web.OCBT/Models/Model/CartBooking/CartBookingModel.cs
KKday.Web.OCBT/Models/Model/Order/JavaOrderInfoModel.cs
KKday.Web.OCBT/Models/Model/Order/OmdlConverter.cs

[OCBT]Bug Fixed:Update OrderDetail Module error
